"""user_email_mfa_recovery

Revision ID: 209424e53e4c
Revises: 973ebe33a9aa
Create Date: 2026-04-16 03:34:36.750129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209424e53e4c'
down_revision: Union[str, None] = '973ebe33a9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('mfa_pin_hash', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('recovery_email', sa.String(length=255), nullable=True))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'recovery_email')
    op.drop_column('users', 'mfa_pin_hash')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
