"""user_nullable_city_onboarding

Revision ID: f33820e80363
Revises: 209424e53e4c
Create Date: 2026-04-16 03:39:03.262373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33820e80363'
down_revision: Union[str, None] = '209424e53e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_step', sa.String(length=30), nullable=False, server_default='city_selection'))
    op.alter_column('users', 'city_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'city_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('users', 'onboarding_step')
    # ### end Alembic commands ###
